ALTER TABLE member
ADD COLUMN IF NOT EXISTS email VARCHAR(255);

ALTER TABLE member
ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255);

ALTER TABLE member
ADD COLUMN IF NOT EXISTS role VARCHAR(50) DEFAULT 'MEMBER';

ALTER TABLE member
ADD COLUMN IF NOT EXISTS enabled BOOLEAN DEFAULT TRUE;